# this will start all the containers in detached mode rebuilding the images (if they exist)
# 1. docker-compose -p comp3095-microservices-ecommerce -f docker-compose.yml up -d

# this second one forces the rebuild of all images, even if they already exist before starting the containers
# 2. docker-compose -p comp3095-microservices-ecommerce -f docker-compose.yml up -d --build
version: '3.9'

services:

  product-service:
    image: product-service
    ports:
      - "8084:8084"
    build:
      context: ./product-service
      dockerfile: ./Dockerfile
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - spring

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/products:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo.init.js:/docker-entrypoint-initdb.d/mongo.init.js:ro
    container_name: mongodb
    command: mongod --auth
    networks:
      - spring

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    container_name: mongo-express
    #restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - spring

volumes:
  mongodb:
    driver: local

networks:
  spring:
    driver: bridge